.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LIQUIDFILES" "1" "November 2013" "" ""
.
.SH "NAME"
\fBliquidfiles\fR \- unix cli interface for LiquidFiles API
.
.SH "SYNOPSIS"
\fBliquidfiles\fR \fIdatabase_name\fR
.
.br
.
.SH "DESCRIPTION"
\fBliquidfiles\fR is a simple command line tool that allows sending emails and files via LiquidFiles API
.
.SH "OPTIONS"
.
.TP
\fB\-a\fR, \fB\-\-api_key=<APK_KEY>\fR
API key for LiquidFiles basic authentication\.
.
.TP
\fB\-u USER\fR
Database username, in first\.last format \fB~/my\.cnf\fR is not correct
.
.TP
\fB\-p PASSWORD\fR
Database password

